services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgre:
    image: postgres:16-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/all

volumes:
  nestjs-learn-node_modules:
  postgres-data: